### ISSUE TITLE
Bug with data-uri less function in release mode

### ISSUE THREAD

**Issue by kalyanov** [csstime/csstime-gulp-tasks#38]
Scenario

1) Less:
```less
.mixin-svg-image (@component, @name) {
  background-image: data-uri('image/svg+xml;charset=UTF-8', 'public@{CDN}/@{component}/svg/@{name}.svg');
}

.icon {
  .mixin-svg-image-src('component-name', 'icon-name');
}
```

2) Build assets in debug mode. CSS:
```css
.icon {
  background-image:url(data:image/svg+xml ...)
}
```

3) Build assets in release mode. CSS:
```css
.icon {
  background-image:url(path_to_svg_instead_data)
}
```
Because css had built before svg appeared in public folder.

I suppose, the problem in different tasks order in release and debug modes.
